# Generated by Django 5.2.3 on 2025-07-03 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("users", "0002_profile_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_articles", to="users.profile"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="users.profile",
            ),
        ),
    ]
