# Generated by Django 5.2.3 on 2025-07-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_favorited_by_alter_article_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "articles",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="articles.article"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
