# Generated by Django 5.2.3 on 2025-07-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="articles",
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="articles.tag"
            ),
        ),
    ]
