# Generated by Django 5.2.3 on 2025-07-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_remove_tag_articles_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
