# Generated by Django 5.2.3 on 2025-07-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_article_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="favorites_count",
        ),
    ]
